// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikpAN3_uXftfzqPUux_uDkMC0a4SrpzE',
    appId: '1:827593425748:web:72bab62bdf12332e9ffec1',
    messagingSenderId: '827593425748',
    projectId: 'atelier4-a-nadiri-iir5gx',
    authDomain: 'atelier4-a-nadiri-iir5gx.firebaseapp.com',
    storageBucket: 'atelier4-a-nadiri-iir5gx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA4XFRRb5BmUXUOxoE8KApX0i8740_cGI',
    appId: '1:827593425748:android:c2e8f45e294d3b819ffec1',
    messagingSenderId: '827593425748',
    projectId: 'atelier4-a-nadiri-iir5gx',
    storageBucket: 'atelier4-a-nadiri-iir5gx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwZieGUX4_yE3jWo7TquJd64DdqUT7qY',
    appId: '1:827593425748:ios:faa93bd48a82a2579ffec1',
    messagingSenderId: '827593425748',
    projectId: 'atelier4-a-nadiri-iir5gx',
    storageBucket: 'atelier4-a-nadiri-iir5gx.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwZieGUX4_yE3jWo7TquJd64DdqUT7qY',
    appId: '1:827593425748:ios:66ca170a1649cebd9ffec1',
    messagingSenderId: '827593425748',
    projectId: 'atelier4-a-nadiri-iir5gx',
    storageBucket: 'atelier4-a-nadiri-iir5gx.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2023.RunnerTests',
  );
}
