// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE2_vz1_MTur-TeKC1_k6xREUp_hUjKsk',
    appId: '1:359460980716:web:f434108ec32e6b3d8ee2c9',
    messagingSenderId: '359460980716',
    projectId: 'atelier4-r-ouassen-iir5g3',
    authDomain: 'atelier4-r-ouassen-iir5g3.firebaseapp.com',
    storageBucket: 'atelier4-r-ouassen-iir5g3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVnZfyVHGfgAZ37gJYcY0eXT9nUYKlSKg',
    appId: '1:359460980716:android:9eef107a1143817d8ee2c9',
    messagingSenderId: '359460980716',
    projectId: 'atelier4-r-ouassen-iir5g3',
    storageBucket: 'atelier4-r-ouassen-iir5g3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmVtbiVUy87wZaJZZcAvL_xPIfIqWXprs',
    appId: '1:359460980716:ios:a6a100e357ea5b408ee2c9',
    messagingSenderId: '359460980716',
    projectId: 'atelier4-r-ouassen-iir5g3',
    storageBucket: 'atelier4-r-ouassen-iir5g3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmVtbiVUy87wZaJZZcAvL_xPIfIqWXprs',
    appId: '1:359460980716:ios:a6a100e357ea5b408ee2c9',
    messagingSenderId: '359460980716',
    projectId: 'atelier4-r-ouassen-iir5g3',
    storageBucket: 'atelier4-r-ouassen-iir5g3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
